name: 🐛 Report an issue
description: Report an issue with NiceTerm
title: "[Bug]: "
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.
      options:
        - label: 'Yes'
          required: true

  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        If you have a feature or enhancement request, please use the [feature request](https://github.com/nyakang/nyaterm/issues/new?template=feature_request.yml).

  - type: textarea
    id: bug
    validations:
      required: true
    attributes:
      label: The bug
      description: >-
        Describe the issue you are experiencing. Tell us what you were trying
        to do, what happened, and what you expected to happen.

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    id: os
    validations:
      required: true
    attributes:
      label: The OS that NiceTerm is running on
      placeholder: Windows 10, Windows 11, macOS 14, Ubuntu 22.04...etc

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version of NiceTerm
      placeholder: v1.0.0

  - type: dropdown
    id: install-method
    validations:
      required: true
    attributes:
      label: Installation method
      options:
        - Downloaded from GitHub Releases
        - Built from source
        - Package manager
        - Other

  - type: input
    id: shell
    attributes:
      label: Shell
      placeholder: PowerShell 7, cmd, zsh, bash, fish...etc

  - type: textarea
    id: repro
    validations:
      required: true
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...

  - type: textarea
    id: logs
    validations:
      required: false
    attributes:
      label: Relevant log output
      description: >-
        Please copy and paste any relevant logs below. Code formatting is
        enabled, no need for backticks.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.

  - type: markdown
    attributes:
      value: Thank you for submitting the form